language: cpp

#safelist of branches where travis should run
branches:
    only:
        - master
os:
  - linux

dist: xenial

compiler:
  - clang
  - gcc

env:
  global:
    - USE_READLINE=OFF
  matrix:
    - CMAKE_BUILD_TYPE=Release
    - CMAKE_BUILD_TYPE=Debug

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: osx
      compiler: clang
      env: CMAKE_BUILD_TYPE=Debug

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgmp-dev
      - libedit-dev
      - bison
      - flex

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew install bison;
        export PATH="/usr/local/opt/bison/bin:$PATH";
      fi

install: skip

before_script:
    - FLAGS="-Wall -Werror"
    - INSTALL=${TRAVIS_BUILD_DIR}/install
    - mkdir build && mkdir ${INSTALL}

script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_CXX_FLAGS="$FLAGS" -DUSE_READLINE:BOOL=${USE_READLINE} -DCMAKE_INSTALL_PREFIX=${INSTALL} ..
  - make
  - ctest
  - make install
  - if [[ ${CMAKE_BUILD_TYPE} == Debug ]]; then
        cd ../regression && ./run-test-notiming.sh ../build/src/bin/opensmt;
        cd ../regression_itp && ./run-tests.sh ../build/src/bin/opensmt;
    fi

  - cd ../examples && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DOPENSMT_DIR=${INSTALL} ..
  - make
